version: '3.8'
services:
  db:
    image: postgres:latest
    container_name: db_school
    environment:
      - POSTGRES_USER=${DATABASE_USER}
      - POSTGRES_PASSWORD=${DATABASE_PASSWORD}
      - POSTGRES_DB={DATABASE_NAME}
    ports:
      - "5243:5432"
    volumes:
      - db-data:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - app-network

  app:
    image: school:1
    container_name: app-container
    depends_on:
      - db
    ports:
      - "3000:3000"
    networks:
      - app-network
    env_file:
      - .env
    environment:
      - DATABASE_URL=postgres://${DATABASE_USER}:${DATABASE_PASSWORD}@db:5432/${DATABASE_NAME}

networks:
  app-network:
    driver: bridge

volumes:
  db-data:
