name: Build and run Docker Locally

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2  

      - name: Build Docker image
        run: docker build -t school-app:latest .

      - name: Run Docker container
        run: docker run -d -p 3000:3000 school-app:latest